[[Extrae]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "178e82591832f0b1ddaa45e88336e40426f74c8d"
libc = "glibc"
os = "linux"

    [[Extrae.download]]
    sha256 = "d05bf1af1fcfece7ce166ae91a1c6b05febe82bc2c2e9d50669b9cc929784670"
    url = "https://github.com/JuliaBinaryWrappers/Extrae_jll.jl/releases/download/Extrae-v4.0.3+0/Extrae.v4.0.3.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[Extrae]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "f601fd7b8c03b417744fd2ad0675996eda29fd1d"
libc = "glibc"
os = "linux"

    [[Extrae.download]]
    sha256 = "51a9e4dabe50fdd8269cc99fc5e86e99cd18c05d1094b666e8cc7a7e00d060a3"
    url = "https://github.com/JuliaBinaryWrappers/Extrae_jll.jl/releases/download/Extrae-v4.0.3+0/Extrae.v4.0.3.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[Extrae]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "1b24453b5fac00cb060a40427411ccf10d95d813"
libc = "glibc"
os = "linux"

    [[Extrae.download]]
    sha256 = "2f4cbda640918ed65771b6716fe74c20f0403dd32281b56887eb71eac6b34916"
    url = "https://github.com/JuliaBinaryWrappers/Extrae_jll.jl/releases/download/Extrae-v4.0.3+0/Extrae.v4.0.3.x86_64-linux-gnu-cuda+none.tar.gz"
[[Extrae]]
arch = "powerpc64le"
cuda = "none"
git-tree-sha1 = "83df439f601bec7fe835dc9fd39764d7d3a47009"
libc = "glibc"
os = "linux"

    [[Extrae.download]]
    sha256 = "dd159e202ebb5e724143b78057f1a5df6c2759e22d8de045776f3ee2560f7b72"
    url = "https://github.com/JuliaBinaryWrappers/Extrae_jll.jl/releases/download/Extrae-v4.0.3+0/Extrae.v4.0.3.powerpc64le-linux-gnu-cuda+none.tar.gz"
[[Extrae]]
arch = "aarch64"
cuda = "none"
git-tree-sha1 = "7855ff878acd55fb372fec67f6250c1ce7220b15"
libc = "glibc"
os = "linux"

    [[Extrae.download]]
    sha256 = "1cb26d13c7b88f484291c678fa3b05d46852e7bdcb5aa8b988e308c946e0e430"
    url = "https://github.com/JuliaBinaryWrappers/Extrae_jll.jl/releases/download/Extrae-v4.0.3+0/Extrae.v4.0.3.aarch64-linux-gnu-cuda+none.tar.gz"
